<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/ksample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#k 
import numpy as np
import pandas as pd

from sklearn.preprocessing import scale
from sklearn.preprocessing import normalize

#model
from sklearn.cluster import KMeans




In [2]:
data =pd.read_excel("university.xlsx")
data.head()

University   SAT  Top10  Accept  SFRatio  \
0                     Harvard University  1310     89      22       13   
1     California Institute of Technology  1415    100      25        6   
2  Massachusetts Institute of Technology  1260     62      59        9   
3                    Stanford University  1310     76      24       12   
4                   Princeton University  1280     83      33       13   

   Expenses  GradRate  
0     22704        94  
1     63575        81  
2     25026        72  
3     31510        88  
4     21864        90

In [3]:
data.isnull().sum()

University    0
SAT           0
Top10         0
Accept        0
SFRatio       0
Expenses      0
GradRate      0
dtype: int64

In [20]:
data1=data.iloc[:,1:]
data1.head()

SAT  Top10  Accept  SFRatio  Expenses  GradRate
0  1310     89      22       13     22704        94
1  1415    100      25        6     63575        81
2  1260     62      59        9     25026        72
3  1310     76      24       12     31510        88
4  1280     83      33       13     21864        90

In [21]:
data1.shape

(100, 6)

In [11]:
data_new =scale(data1)
data_new

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


array([[ 6.32860277e-01,  1.50011672e+00, -8.47758804e-01,
        -1.06559813e+00, -1.49953373e+00,  1.21638361e+00],
       [ 2.80231274e+00,  3.69443640e+00, -3.36033168e-01,
        -2.18224287e+00,  1.29812886e+00, -1.28171859e+00],
       [-4.00212326e-01, -3.88594066e+00,  5.46352405e+00,
        -1.70368084e+00, -1.34059041e+00, -3.01117396e+00],
       [ 6.32860277e-01, -1.09317017e+00, -5.06608380e-01,
        -1.22511881e+00, -8.96753843e-01,  6.34133635e-02],
       [ 1.30167148e-02,  3.03215082e-01,  1.02856853e+00,
        -1.06559813e+00, -1.55703261e+00,  4.47736779e-01],
       [ 1.45931836e+00, -4.94719345e-01, -8.47758804e-01,
         1.64625339e+00, -1.56606814e+00, -3.20910052e-01],
       [ 2.49239096e+00,  5.02698689e-01, -3.36033168e-01,
         5.29608650e-01,  4.98073064e-01,  8.32060194e-01],
       [ 1.25270384e+00, -6.94202952e-01, -3.36033168e-01,
        -1.08474061e-01, -1.22169095e+00, -8.97395175e-01],
       [-1.24733186e+00, -8.93686559e-01, -1.530

In [13]:
data2_new= normalize(data1)
data2_new

array([[5.76023081e-02, 3.91343925e-03, 9.67367005e-04, 5.71625958e-04,
        9.98322750e-01, 4.13329539e-03],
       [2.22516183e-02, 1.57255253e-03, 3.93138133e-04, 9.43531519e-05,
        9.99750272e-01, 1.27376755e-03],
       [5.02834427e-02, 2.47426464e-03, 2.35454216e-03, 3.59167448e-04,
        9.98724949e-01, 2.87333958e-03],
       [4.15379241e-02, 2.40983377e-03, 7.61000137e-04, 3.80500068e-04,
        9.99129763e-01, 2.79033384e-03],
       [5.84426668e-02, 3.78964168e-03, 1.50672500e-03, 5.93558335e-04,
        9.98273803e-01, 4.10925001e-03],
       [6.19998797e-02, 3.62814111e-03, 1.01036841e-03, 1.37777510e-03,
        9.98060285e-01, 3.94962196e-03],
       [2.69718106e-02, 1.61830864e-03, 4.81639476e-04, 4.43108318e-04,
        9.99633099e-01, 1.77243327e-03],
       [5.00059974e-02, 2.91079686e-03, 9.32947713e-04, 7.09040262e-04,
        9.98739185e-01, 3.09738641e-03],
       [2.76736953e-02, 1.74805131e-03, 4.08635370e-04, 5.44847160e-04,
        9.99612923e-01, 

In [0]:
#model
model= KMeans(n_clusters=3)

In [24]:
model.fit(data2_new)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [25]:
model.labels_

array([1, 0, 1, 2, 1, 1, 0, 1, 0, 2, 2, 0, 2, 0, 0, 2, 1, 2, 0, 1, 0, 1,
       1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0,
       1, 2, 0, 0, 0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 0, 0, 2, 0, 2, 1, 0,
       2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 2, 1, 2,
       0, 2, 1, 0, 0, 0, 2, 1, 2, 0, 1, 2], dtype=int32)

In [0]:
# convert 1D to 2D
cluster = pd.DataFrame(model.labels_)

In [27]:
cluster.head()

0
0  1
1  0
2  1
3  2
4  1

In [0]:
data['Tire']= cluster

In [43]:
data.head()

University   SAT  Top10  Accept  SFRatio  \
0                     Harvard University  1310     89      22       13   
1     California Institute of Technology  1415    100      25        6   
2  Massachusetts Institute of Technology  1260     62      59        9   
3                    Stanford University  1310     76      24       12   
4                   Princeton University  1280     83      33       13   

   Expenses  GradRate  Tire  
0     22704        94     1  
1     63575        81     0  
2     25026        72     1  
3     31510        88     2  
4     21864        90     1

In [0]:
data1.to_excel("university.xlsx", sheet_name='sheet2' )

In [45]:
data2=data.iloc[:,[0,7,1,2,3,4,5,6]]
data2

University  Tire   SAT  Top10  \
0                                  Harvard University     1  1310     89   
1                  California Institute of Technology     0  1415    100   
2               Massachusetts Institute of Technology     1  1260     62   
3                                 Stanford University     2  1310     76   
4                                Princeton University     1  1280     83   
5                             University of Cambridge     1  1350     79   
6                                University of Oxford     0  1400     84   
7                  University of California, Berkeley     1  1340     78   
8                             Imperial College London     0  1219     77   
9                                     Yale University     2  1304     76   
10              University of California, Los Angeles     2  1209     84   
11                              University of Chicago     0  1205     75   
12                           Johns Hopkins University     2  1235     86   
13                                 Cornell University     0  1247     83   
14  ETH Zurich – Swiss Federal Institute of T...     0  1224     81   
15                             University of Michigan     2  1236     76   
16                              University of Toronto     1  1307     79   
17                                Columbia University     2  1268     76   
18                         University of Pennsylvania     0  1293     78   
19                         Carnegie Mellon University     1  1292     84   
20                            University of Hong Kong     0  1213     76   
21                          University College London     1  1292     84   
22                           University of Washington     1  1256     87   
23                                    Duke University     0  1267     87   
24                            Northwestern University     0  1343     85   
25                                University of Tokyo     2  1272     86   
26                    Georgia Institute of Technology     0  1201     78   
27        Pohang University of Science and Technology     0  1350     81   
28            University of California, Santa Barbara     2  1335     85   
29                     University of British Columbia     0  1220     85   
..                                                ...   ...   ...    ...   
70                               University of Sydney     1  1261     89   
71                             University of Virginia     0  1340     82   
72                             University of Adelaide     0  1318     79   
73                  University of Southern California     0  1245     78   
74                                     William & Mary     1  1349     87   
75                             Trinity College Dublin     2  1210     76   
76                         King’s College London     0  1278     77   
77                             Stony Brook University     2  1331     87   
78  Korea Advanced Institute of Science and Techno...     0  1328     75   
79                               University of Sussex     2  1347     89   
80                       The University of Queensland     1  1262     86   
81                                 University of York     0  1246     87   
82                              Heidelberg University     0  1306     77   
83                                 University of Utah     0  1301     80   
84                                  Durham University     2  1217     78   
85   London School of Economics and Political Science     2  1237     76   
86                           University of Manchester     1  1288     81   
87               Royal Holloway, University of London     2  1263     87   
88                                    Lund University     0  1283     82   
89                          University of Southampton     2  1252     79   
90                               University of Zurich     1  1227     83   
91             

In [0]:
new =data.groupby('Tire')

In [48]:
new.mean()

SAT      Top10     Accept    SFRatio      Expenses   GradRate
Tire                                                                       
0     1280.577778  81.311111  26.177778  19.088889  58519.400000  87.933333
1     1285.500000  82.050000  27.950000  20.800000  24110.700000  86.500000
2     1274.314286  81.371429  27.428571  19.800000  38442.257143  88.000000