<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/PCAtitanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


In [25]:
data= pd.read_excel("titanic3.xls")
data.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [26]:
data.shape

(1309, 14)

In [27]:
data.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [28]:
data1=data.fillna(data.mean())
data1.head()

pclass  survived  ...        body                        home.dest
0       1         1  ...  160.809917                     St Louis, MO
1       1         1  ...  160.809917  Montreal, PQ / Chesterville, ON
2       1         0  ...  160.809917  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.000000  Montreal, PQ / Chesterville, ON
4       1         0  ...  160.809917  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [29]:
data1.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            0
cabin        1014
embarked        2
boat          823
body            0
home.dest     564
dtype: int64

In [34]:
data2=data1.loc[:,['pclass','survived','age','sibsp','parch','fare','body']]
data2.head()


pclass  survived      age  sibsp  parch      fare        body
0       1         1  29.0000      0      0  211.3375  160.809917
1       1         1   0.9167      1      2  151.5500  160.809917
2       1         0   2.0000      1      2  151.5500  160.809917
3       1         0  30.0000      1      2  151.5500  135.000000
4       1         0  25.0000      1      2  151.5500  160.809917

In [38]:
data3= scale(data2)
data3

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


array([[-1.54609786,  1.27200629, -0.06842022, ..., -0.4449995 ,
         3.4424802 ,  0.        ],
       [-1.54609786,  1.27200629, -2.24909235, ...,  1.86652569,
         2.28647622,  0.        ],
       [-1.54609786, -0.78615963, -2.16497396, ...,  1.86652569,
         2.28647622,  0.        ],
       ...,
       [ 0.84191642, -0.78615963, -0.26254556, ..., -0.4449995 ,
        -0.50407824,  4.84073445],
       [ 0.84191642, -0.78615963, -0.22372049, ..., -0.4449995 ,
        -0.50407824,  0.        ],
       [ 0.84191642, -0.78615963, -0.06842022, ..., -0.4449995 ,
        -0.49151035,  0.        ]])

In [0]:
data3=pd.DataFrame(data3)

In [40]:
data3.head()

0         1         2         3         4         5         6
0 -1.546098  1.272006 -0.068420 -0.479087 -0.445000  3.442480  0.000000
1 -1.546098  1.272006 -2.249092  0.481288  1.866526  2.286476  0.000000
2 -1.546098 -0.786160 -2.164974  0.481288  1.866526  2.286476  0.000000
3 -1.546098 -0.786160  0.009230  0.481288  1.866526  2.286476 -0.872539
4 -1.546098 -0.786160 -0.379021  0.481288  1.866526  2.286476  0.000000

In [0]:
model=PCA()

In [41]:
model.fit(data3)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [42]:
model.components_

array([[-0.6231079 ,  0.37225661,  0.3180344 ,  0.04211829,  0.13921302,
         0.5922744 ,  0.00851431],
       [ 0.162627  ,  0.07896153, -0.42634767,  0.6235516 ,  0.60722718,
         0.16382161, -0.03415018],
       [ 0.00819085, -0.16355593,  0.12608976,  0.04229618,  0.11906881,
        -0.0012332 ,  0.97021434],
       [-0.02506142, -0.75134104,  0.52206874,  0.28373866,  0.13556977,
         0.11669629, -0.22315462],
       [ 0.1938653 ,  0.20470754,  0.38218619, -0.4410823 ,  0.70919774,
        -0.26403609, -0.08493937],
       [-0.07356302, -0.43693783, -0.47857964, -0.57565921,  0.21074798,
         0.44577482, -0.01104171],
       [ 0.73593381,  0.17636993,  0.23134959, -0.03428883, -0.17877977,
         0.58337271,  0.01762951]])

In [0]:
component = pd.DataFrame(model.components_)

In [44]:
component.head()

0         1         2         3         4         5         6
0 -0.623108  0.372257  0.318034  0.042118  0.139213  0.592274  0.008514
1  0.162627  0.078962 -0.426348  0.623552  0.607227  0.163822 -0.034150
2  0.008191 -0.163556  0.126090  0.042296  0.119069 -0.001233  0.970214
3 -0.025061 -0.751341  0.522069  0.283739  0.135570  0.116696 -0.223155
4  0.193865  0.204708  0.382186 -0.441082  0.709198 -0.264036 -0.084939

In [0]:
value=model.explained_variance_ratio_

In [46]:
value

array([0.27092182, 0.22144064, 0.14331557, 0.14030308, 0.09167134,
       0.08096204, 0.05138552])

In [47]:
value.sum()

1.0