<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10,2 )

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [7]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np. ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:

#rand -- Uniform distribution(0,1)
#randn --- normwl distribution  (-1,1)
#randint

In [0]:
np.random.seed(101)

In [12]:
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [13]:
np.random.rand(4,3)

array([[0.68527698, 0.83389686, 0.30696622],
       [0.89361308, 0.72154386, 0.18993895],
       [0.55422759, 0.35213195, 0.1818924 ],
       [0.78560176, 0.96548322, 0.23235366]])

In [14]:
np.random.randn(4)

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651])

In [15]:
np.random.randint(10,50)

22

In [0]:
x=np.random.randint(10,50,10)

In [17]:
x.reshape(2,5)

array([[41, 33, 10, 19, 18],
       [46, 29, 45, 38, 17]])

In [18]:
np.random.randint(1,100,20).reshape(5,4)

array([[11, 53, 57, 39],
       [74, 53, 19, 72],
       [16, 45,  1, 13],
       [18, 76, 80, 98],
       [94, 25, 37, 64]])

In [19]:
x.argmax()

5

In [20]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
a[:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b=a[:6]
b


array([0, 1, 2, 3, 4, 5])

In [24]:
b[:5] =100
b

array([100, 100, 100, 100, 100,   5])

In [25]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
c[1][2]

6

In [28]:
d=np.arange(60).reshape(10,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [29]:
d[1:5,2:6]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [0]:
np.random.seed(101)

In [31]:
a=np.random.randint(0,100,49).reshape(7,7)
a

array([[95, 11, 81, 70, 63, 87, 75],
       [ 9, 77, 40,  4, 63, 40, 60],
       [92, 64,  5, 12, 93, 40, 49],
       [83,  8, 29, 59, 34, 44, 72],
       [19, 10, 76, 95, 87,  0, 73],
       [ 8, 62, 36, 83, 99, 28, 63],
       [ 7, 10, 52, 56, 38, 73, 52]])

In [32]:
a[3,4]

34

In [33]:
a[1:3,0:3]

array([[ 9, 77, 40],
       [92, 64,  5]])

In [34]:
a[:,4]                                                                                     

array([63, 63, 93, 34, 87, 99, 38])

In [35]:
a[[1,3,6]]

array([[ 9, 77, 40,  4, 63, 40, 60],
       [83,  8, 29, 59, 34, 44, 72],
       [ 7, 10, 52, 56, 38, 73, 52]])

In [36]:
a[:,[2,4,6]]

array([[81, 63, 75],
       [40, 63, 60],
       [ 5, 93, 49],
       [29, 34, 72],
       [76, 87, 73],
       [36, 99, 63],
       [52, 38, 52]])

In [37]:
a[[1,3,6],[2,4,6]]

array([40, 34, 52])

In [38]:
a[:,[6,1,3]]

array([[75, 11, 70],
       [60, 77,  4],
       [49, 64, 12],
       [72,  8, 59],
       [73, 10, 95],
       [63, 62, 83],
       [52, 10, 56]])

In [0]:
array = np.arange(0,20)

In [0]:
bool_arr = array > 5

In [41]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [42]:
array[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
array[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
array[array>=11]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [46]:
a*a


array([[9025,  121, 6561, 4900, 3969, 7569, 5625],
       [  81, 5929, 1600,   16, 3969, 1600, 3600],
       [8464, 4096,   25,  144, 8649, 1600, 2401],
       [6889,   64,  841, 3481, 1156, 1936, 5184],
       [ 361,  100, 5776, 9025, 7569,    0, 5329],
       [  64, 3844, 1296, 6889, 9801,  784, 3969],
       [  49,  100, 2704, 3136, 1444, 5329, 2704]])

In [47]:
a**a

array([[-3660930864499998817,         285311670611, -3264474685660004015,
                           0, -4675932718989443137,  1826852818786091687,
         2435553365352800019],
       [           387420489,  5169532022520488509,                    0,
                         256, -4675932718989443137,                    0,
                           0],
       [                   0,                    0,                 3125,
               8916100448256, -7924192819420782515,                    0,
        -2559158286230232783],
       [ 2536461848307888459,             16777216,  5529354540715494413,
         -145357957422043229, -5296008294479953920,                    0,
                           0],
       [ 6353754964178307979,          10000000000,                    0,
        -3660930864499998817,  1826852818786091687,                    1,
        -3116162374727926391],
       [            16777216,  4611686018427387904,                    0,
         2536461848307888459, -

In [48]:
a

array([[95, 11, 81, 70, 63, 87, 75],
       [ 9, 77, 40,  4, 63, 40, 60],
       [92, 64,  5, 12, 93, 40, 49],
       [83,  8, 29, 59, 34, 44, 72],
       [19, 10, 76, 95, 87,  0, 73],
       [ 8, 62, 36, 83, 99, 28, 63],
       [ 7, 10, 52, 56, 38, 73, 52]])

In [49]:
np.sin(a)

array([[ 0.68326171, -0.99999021, -0.62988799,  0.77389068,  0.1673557 ,
        -0.82181784, -0.38778164],
       [ 0.41211849,  0.99952016,  0.74511316, -0.7568025 ,  0.1673557 ,
         0.74511316, -0.30481062],
       [-0.77946607,  0.92002604, -0.95892427, -0.53657292, -0.94828214,
         0.74511316, -0.95375265],
       [ 0.96836446,  0.98935825, -0.66363388,  0.63673801,  0.52908269,
         0.01770193,  0.25382336],
       [ 0.14987721, -0.54402111,  0.56610764,  0.68326171, -0.82181784,
         0.        , -0.67677196],
       [ 0.98935825, -0.7391807 , -0.99177885,  0.96836446, -0.99920683,
         0.27090579,  0.1673557 ],
       [ 0.6569866 , -0.54402111,  0.98662759, -0.521551  ,  0.29636858,
        -0.67677196,  0.98662759]])

In [50]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[4.55387689, 2.39789527, 4.39444915, 4.24849524, 4.14313473,
        4.46590812, 4.31748811],
       [2.19722458, 4.34380542, 3.68887945, 1.38629436, 4.14313473,
        3.68887945, 4.09434456],
       [4.52178858, 4.15888308, 1.60943791, 2.48490665, 4.53259949,
        3.68887945, 3.8918203 ],
       [4.41884061, 2.07944154, 3.36729583, 4.07753744, 3.52636052,
        3.78418963, 4.27666612],
       [2.94443898, 2.30258509, 4.33073334, 4.55387689, 4.46590812,
              -inf, 4.29045944],
       [2.07944154, 4.12713439, 3.58351894, 4.41884061, 4.59511985,
        3.33220451, 4.14313473],
       [1.94591015, 2.30258509, 3.95124372, 4.02535169, 3.63758616,
        4.29045944, 3.95124372]])

In [51]:
pd.Series(data = (1,2,3,4,5))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [0]:
d={'a':1,'b':2,'c':3}

In [53]:
pd.Series(data=d)

a    1
b    2
c    3
dtype: int64

In [54]:
l=[1,2,3,4]
pd.Series(data=l, index= 'a b c d'.split())

a    1
b    2
c    3
d    4
dtype: int64

In [55]:
count1 = pd.Series([1,2],['USA','INDIA'])
count2 = pd.Series([1,2],['USA','japan'])
print(count1/count2)

INDIA    NaN
USA      1.0
japan    NaN
dtype: float64


In [56]:
np.(10)

SyntaxError: ignored

In [0]:
np.arange(10,51)

In [0]:
np.arange(10,51,2)

In [0]:
np.ones(10)*5

In [0]:
np.arange(0,9).reshape(3,3)

In [0]:
x= np.eye(3,3)
x

In [0]:
np.random.rand(1)

In [0]:
np.random.randn(25).reshape(5,5)

In [0]:
np.linspace(0,1,20)

In [0]:
np.linspace(0.1,1)

In [0]:
np.arange(1,101).reshape(10,10) / 100

In [0]:
mat = np.arange(1,26).reshape(5,5)
mat

In [0]:
mat[2:5,1:5]

In [0]:
mat[3,4]

In [0]:
mat[0:3:,1]

In [0]:
mat[4,:]

In [0]:
mat[3:5,:]

In [0]:
mat.sum()

In [0]:
mat.std()

In [0]:
mat.sum(axis=0)