<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import numpy as np
import pandas as pd

x = np.array([1,2,3])
x

array([1, 2, 3])

In [0]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [0]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(0,10,2
          
          
          
         
         
         
         )

array([0, 2, 4, 6, 8])

In [0]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [0]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np. ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:

#rand -- Uniform distribution(0,1)
#randn --- normwl distribution  (-1,1)
#randint

In [0]:
np.random.seed(101)

In [0]:
np.random.rand(4)

array([0.1956727 , 0.02169302, 0.85348955, 0.00937033])

In [0]:
np.random.rand(4,3)

array([[0.23229435, 0.64069896, 0.04170757],
       [0.58002913, 0.44698245, 0.17130255],
       [0.92045602, 0.742356  , 0.75172003],
       [0.90896988, 0.8645956 , 0.19949379]])

In [0]:
np.random.randn(4)

array([-1.29273007, -0.43299935,  0.63546509,  0.31728237])

In [0]:
np.random.randint(10,50)

21

In [0]:
x=np.random.randint(10,50,10)

In [0]:
x.reshape(2,5)

array([[27, 21, 25, 43, 39],
       [34, 46, 29, 45, 40]])

In [0]:
np.random.randint(1,100,20).reshape(5,4)

array([[95, 36, 29,  4],
       [84, 85, 48, 15],
       [70, 61, 70, 52],
       [ 7, 89, 72, 69],
       [24, 36, 80, 99]])

In [0]:
x.argmax()

6

In [48]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
a[:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
b=a[:6]
b


array([0, 1, 2, 3, 4, 5])

99

In [70]:
b[:5] =100
b

array([100, 100, 100, 100, 100,   5])

In [71]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
c[1][2]

6

In [85]:
d=np.arange(60).reshape(10,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [92]:
d[1:5,2:6]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [0]:
np.random.seed(101)

In [88]:
a=np.random.randint(0,100,49).reshape(7,7)
a

array([[95, 11, 81, 70, 63, 87, 75],
       [ 9, 77, 40,  4, 63, 40, 60],
       [92, 64,  5, 12, 93, 40, 49],
       [83,  8, 29, 59, 34, 44, 72],
       [19, 10, 76, 95, 87,  0, 73],
       [ 8, 62, 36, 83, 99, 28, 63],
       [ 7, 10, 52, 56, 38, 73, 52]])

In [89]:
a[3,4]

34

In [99]:
a[1:3,0:3]

array([[ 9, 77, 40],
       [92, 64,  5]])

In [104]:
a[:,4]                                                                                     

array([63, 63, 93, 34, 87, 99, 38])

In [102]:
a[[1,3,6]]

array([[ 9, 77, 40,  4, 63, 40, 60],
       [83,  8, 29, 59, 34, 44, 72],
       [ 7, 10, 52, 56, 38, 73, 52]])

In [105]:
a[:,[2,4,6]]

array([[81, 63, 75],
       [40, 63, 60],
       [ 5, 93, 49],
       [29, 34, 72],
       [76, 87, 73],
       [36, 99, 63],
       [52, 38, 52]])

In [108]:
a[[1,3,6],[2,4,6]]

array([40, 34, 52])

In [110]:
a[:,[6,1,3]]

array([[75, 11, 70],
       [60, 77,  4],
       [49, 64, 12],
       [72,  8, 59],
       [73, 10, 95],
       [63, 62, 83],
       [52, 10, 56]])

In [0]:
array = np.arange(0,20)

In [0]:
bool_arr = array > 5

In [116]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [117]:
array[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [118]:
array[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [120]:
array[array>=11]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [123]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [127]:
a*a


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [131]:
a**a

array([                   1,                    1,                    4,
                         27,                  256,                 3125,
                      46656,               823543,             16777216,
                  387420489,          10000000000,         285311670611,
              8916100448256,      302875106592253,    11112006825558016,
         437893890380859375,                    0, -2863221430593058543,
        -497033925936021504,  6353754964178307979])

In [132]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [134]:
np.log(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [138]:
pd.Series(data = (1,2,3,4,5))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [0]:
d={'a':1,'b':2,'c':3}

In [143]:
pd.Series(data=d)

a    1
b    2
c    3
dtype: int64

In [151]:
l=[1,2,3,4]
pd.Series(data=l, index= 'a b c d'.split())

a    1
b    2
c    3
d    4
dtype: int64

In [169]:
count1 = pd.Series([1,2],['USA','INDIA'])
count2 = pd.Series([1,2],['USA','japan'])
print(count1/count2)

INDIA    NaN
USA      1.0
japan    NaN
dtype: float64


In [174]:
np.(10)

SyntaxError: ignored

In [182]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [183]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [187]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [191]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [194]:
x= np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
np.random.rand(1)

array([0.67969926])

In [198]:
np.random.randn(25).reshape(5,5)

array([[ 3.01467586, -0.13916998,  0.48231093,  0.9779388 , -0.34443117],
       [-1.78506786,  0.53094881,  0.62836446,  2.28326095,  0.14891159],
       [ 0.53617481,  0.14488268, -0.6278791 ,  1.15189818,  0.25936989],
       [-1.1865266 , -0.67386085, -1.55511943, -0.56660415, -0.790608  ],
       [ 0.2307624 ,  1.02801241, -0.8882423 , -2.14168659, -0.97607635]])

In [204]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [216]:
np.linspace(0.1,1)

array([0.1       , 0.11836735, 0.13673469, 0.15510204, 0.17346939,
       0.19183673, 0.21020408, 0.22857143, 0.24693878, 0.26530612,
       0.28367347, 0.30204082, 0.32040816, 0.33877551, 0.35714286,
       0.3755102 , 0.39387755, 0.4122449 , 0.43061224, 0.44897959,
       0.46734694, 0.48571429, 0.50408163, 0.52244898, 0.54081633,
       0.55918367, 0.57755102, 0.59591837, 0.61428571, 0.63265306,
       0.65102041, 0.66938776, 0.6877551 , 0.70612245, 0.7244898 ,
       0.74285714, 0.76122449, 0.77959184, 0.79795918, 0.81632653,
       0.83469388, 0.85306122, 0.87142857, 0.88979592, 0.90816327,
       0.92653061, 0.94489796, 0.96326531, 0.98163265, 1.        ])

In [217]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [218]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [221]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [222]:
mat[3,4]

20

In [224]:
mat[0:3:,1]

array([ 2,  7, 12])

In [225]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [226]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [227]:
mat.sum()

325

In [228]:
mat.std()

7.211102550927978

In [229]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])