<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/PrincipleComponentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principle Component Analysis


In [0]:
#
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

from sklearn.preprocessing import scale
from sklearn.preprocessing import normalize

#model
from sklearn.decomposition import PCA



In [22]:
data=pd.read_excel("universitynew.xlsx")
data.head()

University   SAT  Top10  Accept  SFRatio  \
0                     Harvard University  1310     89      22       13   
1     California Institute of Technology  1415    100      25        6   
2  Massachusetts Institute of Technology  1260     62      59        9   
3                    Stanford University  1310     76      24       12   
4                   Princeton University  1280     83      33       13   

   Expenses  GradRate  
0     22704        94  
1     63575        81  
2     25026        72  
3     31510        88  
4     21864        90

In [23]:
data1=data.iloc[:,1:]
data1.head()

SAT  Top10  Accept  SFRatio  Expenses  GradRate
0  1310     89      22       13     22704        94
1  1415    100      25        6     63575        81
2  1260     62      59        9     25026        72
3  1310     76      24       12     31510        88
4  1280     83      33       13     21864        90

In [29]:
data1= scale(data1)
data1

array([[ 6.32860277e-01,  1.50011672e+00, -8.47758804e-01,
        -1.06559813e+00, -1.49953373e+00,  1.21638361e+00],
       [ 2.80231274e+00,  3.69443640e+00, -3.36033168e-01,
        -2.18224287e+00,  1.29812886e+00, -1.28171859e+00],
       [-4.00212326e-01, -3.88594066e+00,  5.46352405e+00,
        -1.70368084e+00, -1.34059041e+00, -3.01117396e+00],
       [ 6.32860277e-01, -1.09317017e+00, -5.06608380e-01,
        -1.22511881e+00, -8.96753843e-01,  6.34133635e-02],
       [ 1.30167148e-02,  3.03215082e-01,  1.02856853e+00,
        -1.06559813e+00, -1.55703261e+00,  4.47736779e-01],
       [ 1.45931836e+00, -4.94719345e-01, -8.47758804e-01,
         1.64625339e+00, -1.56606814e+00, -3.20910052e-01],
       [ 2.49239096e+00,  5.02698689e-01, -3.36033168e-01,
         5.29608650e-01,  4.98073064e-01,  8.32060194e-01],
       [ 1.25270384e+00, -6.94202952e-01, -3.36033168e-01,
        -1.08474061e-01, -1.22169095e+00, -8.97395175e-01],
       [-1.24733186e+00, -8.93686559e-01, -1.530

In [0]:
data1=pd.DataFrame(data1)

In [26]:
data1.head()

0         1         2         3         4         5
0  0.632860  1.500117 -0.847759 -1.065598 -1.499534  1.216384
1  2.802313  3.694436 -0.336033 -2.182243  1.298129 -1.281719
2 -0.400212 -3.885941  5.463524 -1.703681 -1.340590 -3.011174
3  0.632860 -1.093170 -0.506608 -1.225119 -0.896754  0.063413
4  0.013017  0.303215  1.028569 -1.065598 -1.557033  0.447737

In [0]:
model=PCA()

In [28]:
model.fit(data1)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [31]:
model.components_

array([[ 0.10540976, -0.18438361,  0.58125243, -0.47450123, -0.13493754,
        -0.61129169],
       [ 0.65920969,  0.6920139 , -0.17804806, -0.05368063, -0.11374753,
        -0.19758067],
       [-0.00126588,  0.0387435 , -0.2212484 , -0.51382021,  0.82794735,
        -0.00620183],
       [-0.63664663,  0.41283798, -0.2887001 , -0.44191458, -0.37231631,
        -0.0836074 ],
       [-0.04557567, -0.27961619, -0.57958081,  0.28939417,  0.03244143,
        -0.70641511],
       [ 0.3833193 , -0.48682437, -0.40278033, -0.47845406, -0.3790576 ,
         0.28501473]])

In [0]:
component = pd.DataFrame(model.components_)

In [33]:
component.head()

0         1         2         3         4         5
0  0.105410 -0.184384  0.581252 -0.474501 -0.134938 -0.611292
1  0.659210  0.692014 -0.178048 -0.053681 -0.113748 -0.197581
2 -0.001266  0.038744 -0.221248 -0.513820  0.827947 -0.006202
3 -0.636647  0.412838 -0.288700 -0.441915 -0.372316 -0.083607
4 -0.045576 -0.279616 -0.579581  0.289394  0.032441 -0.706415

In [0]:
value=model.explained_variance_ratio_

In [35]:
value

array([0.25857915, 0.21110352, 0.18220855, 0.13982004, 0.10506738,
       0.10322136])

In [36]:
value.sum()

1.0