<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/pythonprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
s=np.arange(18).reshape(6,3)
print(s)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [7]:
planet ='Earth'
diameter=12742
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


In [11]:
s="hi this is shyam"
s.split()

['hi', 'this', 'is', 'shyam']

In [21]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2]

['hello']