<a href="https://colab.research.google.com/github/Meghashyamt/python/blob/master/pythonprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
s=np.arange(18).reshape(6,3)
print(s)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [0]:
planet ='Earth'
diameter=12742
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


In [0]:
s="hi this is shyam"
s.split()

['hi', 'this', 'is', 'shyam']

In [0]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2]

['hello']

In [0]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [0]:
def domainGet(email):
 return email.split('@')[1]
domainGet('user@domain.com')

'domain.com'

In [0]:
def findDog(string):
 return 'dog' in string.lower().split()
findDog('Is there a dog here?')

True

In [0]:
def countDog(string):
 count = 0
 for word in string.lower().split():
   if word == 'dog':
     count += 1
 return count
countDog('This dog runs faster than the other dog dude!')

2

In [0]:
seq = ['soup','dog','salad','cat','great']
list(filter(lambda letter: letter[:][0] == 's', seq))


['soup', 'salad']

In [0]:
def caught_speeding(speed, is_birthday):
 if is_birthday:
  speeding = speed - 5
 else:
  speeding = speed
 if speeding <= 60:
  print("No Ticket")
 elif (speeding >= 61) and (speeding <= 80):
  print("Small Ticket")
 else:
  print("Big Ticket")
caught_speeding(81,False)

Big Ticket


In [0]:
cars=pd.read_csv("cars.csv")
cars.head()

car_model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2